### ISSUE TITLE
Communicating the new application/selection process

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/nazareth-outreach#11]
Yesterday the selection committee met and approved significant changes to the application and selection processes at all campuses: https://github.com/foundersandcoders/selection-committee/blob/5a304c8d7d7b7e81249935bfb6763d979304f459/process.md

**Critically:**
- We will be opening applications next week for the October course, and interviewing all applicants in late July (I'll be in Israel for most of the month). 
- Applicants do not need to complete prerequisites before applying, they just need working accounts on GitHub/Codewars/FCC. 
- From the interviews, we'll select a group of about 12 people who will go through an 8 week, once a week (probably three hour sessions) prep-course that provides support for prerequisites. 
- All those from this course who complete the prerequisites will be offered spots on the programme beginning October 29.

**As a Nazareth programme, we have a number things to work out to make this process a success, such as:**
- An outreach plan to get the word out about the revised process - @shiryz has already offered to translate the new application page into Arabic and Hebrew, and to help prepare FB ads in both languages - but we will need a small army to share posts and call/text/email people + organisations who should know about this opportunity
- Whether to maintain our current FB group (in addition to the FB page for FAC Nazareth)
- Volunteers to coordinate and lead the prep-course
- A basic curriculum structure for the prep-course (which can be done in coordination with Gaza but will ultimately need to be based on the needs of the students)

Please fill out [this doodle](https://doodle.com/poll/c2kfeicceph8cxex) if you are interested in being a part of this planning process _and_ have time to join a hangout early next week. Unfortunately, I'm in California and 10 hours behind all of you, which means most of the times I'm available conflict with Iftar. If none of these work, please suggest a time that would be better for all of you).

**Comment by shiryz** [comment]
We have the iftar on the 20th, so if you're going chances are you can't make it to the meeting.

**Comment by rebeccaradding** [comment]
@shiryz good point. It looks like Sunday at 7:00 is winning...

**Comment by rebeccaradding** [comment]
@Karyum @esraajb @shiryz @RQ16 @hilbertspitzer

All who filled out the Doodle should have received a calendar invite for tomorrow at 19:00. Talk to you then!
