### ISSUE TITLE
Outreach to FB groups for FACN3 application

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/nazareth-outreach#13]
Mario, Esraa, Reem, Joudy, and Suha:

In the comments, please post links to **at least three** Facebook groups you are prepared to share the application and/or C4E information with during the next month. By sharing our plans, we can be sure not to overlap so that we cover as much ground as possible (I'll post groups I've used before as well, in case any of you want to take them on and/or write posts for those groups in Arabic/Hebrew).

Please post your plans by **Tuesday night (June 20)** so that we are ready to go with ad spamming on Wednesday!

Shireen, Mohamed, and Hiba - although you weren't on our call, we welcome your contributions to this project!

**Comment by Karyum** [comment]
[my sister's group](https://www.facebook.com/groups/1610752825917253/)

[Programming QA](https://www.facebook.com/groups/1714430195474379/?ref=group_browse_new)

[ATLink](https://www.facebook.com/groups/ATLinkForum/?ref=group_browse_new)

[Tel aviv students and graduates](https://www.facebook.com/groups/1602350700020304/?ref=group_browse_new)

[Hasoub Community](https://www.facebook.com/groups/HasoubCommunity/?ref=group_browse_new)

[Kav Mashve](https://www.facebook.com/groups/kav.mashve.junior/?ref=group_browse_new)

[Arab students Forum](https://www.facebook.com/groups/908629509205148/?ref=group_browse_new)

[MakeathonGo](https://www.facebook.com/groups/TheMakeathon/?ref=group_browse_new)

[Tsofen mentoring program](https://www.facebook.com/groups/687460291412105/?ref=group_browse_new)

[Microsoft Nazareth academy](https://www.facebook.com/groups/170760973334897/?ref=group_browse_new)

**Comment by HilbertSpitzer** [comment]
Rebecca, what groups were you thinking of?
I don't use facebook unless if it's for the simple act of talking to my far away relatives.
So yeah, giving me advise would be much advised

How do we go on the ad spamming thing?

**Comment by rebeccaradding** [comment]
@HilbertSpitzer if you don't use FB, we welcome other ideas for places to advertise the application - local libraries, schools, mosques, churches, community centers - or other online platforms, like Reddit. What do people use in Israel?

**Comment by esraajb** [comment]
https://www.facebook.com/MagicalNazareth/

Groups we should find:
* Arab students at the Technion
* Arab students at Haifa University
* Arab students in colleges in the north
* Haifa specific group
* Shfamr specific group

**Comment by shiryz** [comment]
Technion groups:

[main students group](https://www.facebook.com/groups/technionstudents/)
[main women's goup](https://www.facebook.com/groups/technionstudentswomen/)
[Arab students main group](https://www.facebook.com/groups/252255494796536/?fref=nf )
[another group for arab students](https://www.facebook.com/groups/1552440831710311/)
[arab female srudents group](https://www.facebook.com/groups/231747010357652/)

**Comment by rebeccaradding** [comment]
- [MEET](https://www.facebook.com/MEET.entrepreneurs.of.tomorrow/) - contact Golde Orlan
- [PIP](https://www.facebook.com/PalestinianInternshipProgram/)
- [Kav Mashve](https://www.facebook.com/Kav-Mashve-%D9%83%D8%A7%D9%81-%D9%85%D8%B4%D9%81%D9%8A%D9%87-%D7%A7%D7%95-%D7%9E%D7%A9%D7%95%D7%95%D7%94-65349096060/) 
- [Collective Impact](https://www.facebook.com/CollectiveImpact/) - will contact [Khalil Mari](https://www.facebook.com/Khalil.Mari)
- [Sikkuy](https://www.facebook.com/sikkuy/) - Also Khalil Mari
- [Abraham Fund](https://facebook.com/theabrahamfund/) - will contact Orni Petrushka/Lilli Stern
- [Tishreen Association](https://facebook.com/TishreenPage/)
- [Kayan Feminist Organisation](https://facebook.com/KayanFeministOrg/)
- [FIDEL](https://facebook.com/fidel.israel/)
- [Schoolhouse TLV](https://www.facebook.com/TheSchoolhouse4refugees/) - contact Uri Shamgar
- [MOONA](https://www.facebook.com/MoonaASpaceForChange/)
- [Takwin Labs](https://www.facebook.com/TakwinLabs/)
- [Mobile Monday Nazareth](https://www.facebook.com/groups/MoMoNaz/) - contact Hans Shakur
- [Microsoft Nazareth Academy](https://www.facebook.com/groups/170760973334897/)
- [Nazareth Startup Founders](https://facebook.com/NazForum/) - contact Fadi Swidan
- [BEER - Tech Haifa](https://www.facebook.com/BeerTechHaifa/?fref=pb&hc_location=profile_browser)
- [In-vent the Haifa Hub](https://www.facebook.com/inventhub/?fref=pb&hc_location=profile_browser)
- [She Codes](https://facebook.com/codesshe/) - contact Noa Muzzafi
- [My Pink Electronics](https://www.facebook.com/MyPinkElectronics/?fref=pb&hc_location=profile_browser)
- [The Hive - Ashdod](https://www.facebook.com/TheHiveAshdodByGvahim/?fref=pb&hc_location=profile_browser)
- [TRI/O Tech](https://www.facebook.com/TRIOTechHub/?fref=pb&hc_location=profile_browser)
- [Oranim Academic College](https://www.facebook.com/pages/Oranim-Academic-College/107524469270989?fref=pb&hc_location=profile_browser)
- [StarTau](https://www.facebook.com/startau/?fref=pb&hc_location=profile_browser)
- [PresenTense](https://www.facebook.com/startau/?fref=pb&hc_location=profile_browser)
- [Hybrid](https://www.facebook.com/The.Hybrid.Accelerator/?fref=pb&hc_location=profile_browser)
- [Maantech](https://www.facebook.com/Maantech.coalition/?fref=pb&hc_location=profile_browser)
- [UK Task Force](https://www.facebook.com/UkTaskForce/?fref=pb&hc_location=profile_browser)
- [InnDigital](https://www.facebook.com/innDigitalServices/?fref=pb&hc_location=profile_browser)
- [Bitech](https://www.facebook.com/bitech2017/?fref=pb&hc_location=profile_browser)

Action point for when we're done with this round: create a file with a comprehensive list of all groups we work with to promote the application. Will make this speedier next time!

**Comment by Jbarget** [comment]
This is incredibly well coordinated, well done to all involved!

**Comment by HilbertSpitzer** [comment]
May I ask how did you tackle this? Who said what and where? What reactions did you all get?

**Comment by rebeccaradding** [comment]
@esraajb @shiryz have you done any outreach to the groups you listed?

**Comment by esraajb** [comment]
I didn't

**Comment by HilbertSpitzer** [comment]
Unless you are talking to someone you already know or someone who already knows FAC, then the majority of your time advertising one-on-one on any group listed will be wasted.
And as popular as English is, sometimes, we do need a good speaker of Hebrew or Arabic to leave  good impression
If it's not someone you personally know then you need to think carefully about how to appeal to the people you're talking with, and each person or group is likely to need a different way of appealing to it, each on its own. The other side has to know your character and the direction you're trying to take with them. So whatever account it is that you're using to advertise, it needs to be genuine and directed especially towards advertising and not just an account with your real name on it, and you need to think of something that would especially appeal to the one you're talking to, each group, each category, each division, each according to what they care about. Reliance on the masses isn't enough. But of course, this is easier said than done

**Comment by rebeccaradding** [comment]
@HilbertSpitzer would be great for you to collaborate with @paulhanna1933 @matthewdking who are working on social media to help them with this messaging/making connections.

**Comment by rebeccaradding** [comment]
See: https://github.com/foundersandcoders/nazareth-programme/pull/182

Will close this issue once we have that file up!
