### ISSUE TITLE
FACN3 Prospective applicant meetup in Haifa

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/nazareth-outreach#14]
@karyum @esraajb please post your plans here by Saturday, June 24 so we can start advertising next week!

**Comment by rebeccaradding** [comment]
Any updates?

**Comment by esraajb** [comment]
@Karyum do you wanna take the lead and look for a place where we can hold the meetup?
preferably a place that is accessible also to the students who live near the University.

I'm happy then to advertise it to my friends who live in Haifa.

**Comment by rebeccaradding** [comment]
@esraajb is this place too far from the university? 

http://www3.haifa.muni.il/inventuipub/

**Comment by esraajb** [comment]
No, it's in the downtown.

**Comment by Karyum** [comment]
hey @esraajb  do we want it to be next to the University ? isn't it summer break soon ( or already began im not sure ) and exams time ?? so there would no students in the University until October.

**Comment by rebeccaradding** [comment]
@Karyum @esraajb it appears that has not happened, I'm going to reopen it as an issue for the `outreach` task group.
