### ISSUE TITLE
Post our meetups on meetup.com

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/nazareth-outreach#19]
Israel's largest meetups are Tech related. Even if meetup.com isn't used as much as facebook, it wouldn't hurt for us to have a presence on there.

![largest-israel-meetups](https://user-images.githubusercontent.com/15656538/27276349-de6dee50-54d2-11e7-9bd5-078930f2722a.png)

+ [ ] Start posting all our Coding for Everyone meetups (and the prep course, when it begins)
+ [ ] Give "event organiser" status to everyone from FACN1 who is organising a new meetup

Two options:
1. Start advertising Nazareth meetups under the same organisation as the London meetups
    + Participants who subscribe to our the FAC meetup organisation will get notifications about meetups that are happening in a different country from them. This could get annoying, feel like spam, and turn people off
    + If the meetup organisation is being managed centrally (FCI), then managing one organisation is easier
2. Create a "Founders and Coders - Nazareth" organisation & rename the existing one "Founders and Coders - London"
    + More obvious to Nazarines joining the organisation, that our meetups are not held in London (see picture below)
    + Admin is simpler - you only see messages from people who are in your city
    + If the meetup organisation is being managed by the local business development task groups, this provides a greater sense of ownership & less confusion over autonomy
    + Doesn't scale well - you can have up to 3 organisations with a free account

@rebeccaradding thoughts?

**Comment by rebeccaradding** [comment]
@jsms90 I prefer option 2, for the first three reasons listed - the not scaling well part can be addressed later when we _hopefully_ have more money, haha. 

Assigning @esraajb @HilbertSpitzer @Karyum who as I understand have all been very active in C4E Nazareth.

**Comment by jsms90** [comment]
@rebeccaradding I was talking nonsense about opening organisations for free.
https://www.meetup.com/pricing/ - $9.99 per month for a new one.

**Comment by rebeccaradding** [comment]
@jsms90 eeeek that's not amazing but if/when we have money it makes sense. Would anyone be willing to lend Nazareth some spare change for a couple of months haha? 

I definitely don't think we should start advertising Nazareth meetups under the London account.

**Comment by rebeccaradding** [comment]
@jsms90 relocating issue: https://github.com/foundersandcoders/nazareth-programme/issues/178
