### ISSUE TITLE
FACN open day 

### ISSUE THREAD

**Issue by shiryz** [foundersandcoders/nazareth-outreach#20]
Host an event similar to the one @rebeccaradding and @sofer had before facn1 (mentioned [here](https://github.com/foundersandcoders/london-programme/issues/124)), talk to potential applicants, showcase the projects and introduce the new application process and the prep-course.
We can host it after the Eid (June 27), this will attract students who have heard about the program but don't understand what it is.
Our advertisement options are through our partners (NTCA, tsofen, hasoub, UKITH), facebook, instagram (we can have paid ads here as well), meetup and inviting people in person...

**Comment by rebeccaradding** [comment]
@shiryz we are currently trying to plan a kickoff event for July 1 for FACN2 in partnership with UKITH and Tsofen. 

I'm not sure it makes sense for us to do two events in the same short time frame, but this kickoff event can certainly function as an open evening as alumni + new students will be in attendance, as well as our partners. 

What do you think? Also, would you advise pushing the date to Thursday, July 6 instead, given our short time frame?

**Comment by shiryz** [comment]
It definitely can function as both :+1:.
Yes, pushing it makes sense, by then we would have introduced the students to fac and they'd be more comfortable participating :smile:.

**Comment by rebeccaradding** [comment]
@shiryz, @sofer and I agree and I have contacted UKITH, NCTA, and Tsofen about changing the date. NCTA already has expressed support. Will update you here and aim to have an invite for this before Friday.

**Comment by rebeccaradding** [comment]
@shiryz invite here: http://fac2017.eventbrite.com

**Comment by shiryz** [comment]
closing, the event was yesterday.
