### ISSUE TITLE
Communication with applicants to FACN3

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/nazareth-outreach#23]
I'm not sure if this issue belongs here or in `nazareth-selection`, but given that we already have two local and one international applicant to FACN3 (in the first 48 hours!), I wanted to open an issue around next steps. In particular, I plan to draft an email which includes:

- A thank-you for their application and reminder that we will contact them in late July to schedule an interview
- A reminder to local applicants that we offer a weekly meetup where they can get help with prerequisites
- An invitation to the C4E Nazareth Gitter channel

Would it also make sense to call local applicants to invite them personally to C4E (this is something @esraajb has done in the past)? If so, would anyone from FACN1 be willing to take on this task (which would include checking the application form regularly for new applicants)? 

@Karyum @MohamedOmarii @HilbertSpitzer @Suuuuha @RQ16 @hibaakel

**Comment by rebeccaradding** [comment]
Here's what I have so for for the letter to applicants. Feedback?

---

Dear <<name>>,

Thank you for your application to the Founders & Coders Nazareth course beginning October 29. We will be following up in late July to schedule an interview. 

In the meantime, we encourage you to start or continue work on our course prerequisites. 

If you live in or near Nazareth, please join us at Coding for Everyone, every Monday at 6:30 PM at the Khan el-Basha building in Nazareth. At our weekly meetup, you will meet current Founders & Coders students and alumni and can work with fellow applicants on course prerequisites.

Whether you're near or far, please also join our Coding for Everyone - Nazareth channel on Gitter. At Founders & Coders Nazareth, we look for applicants who share their learning, so we expect applicants to either attend our meetups, participate on Gitter, or both.

Please do not hesitate to reach out if you have any questions in advance of your interview.

Kindest regards,

Rebecca

**Comment by HilbertSpitzer** [comment]
Shouldn't you also add the phone number of someone to contact (Esraa)? And maybe the name of the mentor most active at C4E (Mario)?

If you really want said person to start, then make i convenient and add links "to start or continue [work](https://github.com/foundersandcoders/recommended-materials) on our course [prerequisites](https://foundersandcoders.com/apply/prerequisites/)", and also adding the C4E gitter channel, which I assume [is this](https://gitter.im/codingforeveryone/nazareth)

The [Khan el-Basha building](https://www.google.co.il/maps/place/Khan+El+Basha/@32.7015487,35.2970921,3a,75y,264.33h,83.44t,-0.32r/data=!3m6!1e1!3m4!1sb1wMdc7iT1guDW92BvEoGQ!2e0!7i13312!8i6656!4m12!1m6!3m5!1s0x151c4dd353daffff:0xd3ad58016b38181f!2sKhan+El+Basha!8m2!3d32.7013951!4d35.296929!3m4!1s0x151c4dd353daffff:0xd3ad58016b38181f!8m2!3d32.7013951!4d35.296929?hl=en) is not [well-known](https://www.google.co.il/maps/@32.7015487,35.2970921,3a,75y,239.51h,76.09t,0.18r/data=!3m6!1e1!3m4!1s_wXr0pAaLMknqURV8Ej-NQ!2e0!7i13312!8i6656?hl=en) in Nazareth, I know from experience. A better way to direct someone there would be to point out that it's located slightly below the Casanova Hotel in Nazareth, it's kinda a landmark, a [nearby sign](https://www.google.co.il/maps/place/Khan+El+Basha/@32.7022425,35.2971932,3a,75y,199.22h,71.75t/data=!3m6!1e1!3m4!1svuGSZY3QveueMUdDmr_lCg!2e0!7i13312!8i6656!4m12!1m6!3m5!1s0x151c4dd353daffff:0xd3ad58016b38181f!2sKhan+El+Basha!8m2!3d32.7013951!4d35.296929!3m4!1s0x151c4dd353daffff:0xd3ad58016b38181f!8m2!3d32.7013951!4d35.296929?hl=en) specifies its name. Both the Casa Nova and Khan el Basha are near [Mazzawi Nazarene](https://www.google.co.il/maps/@32.7016442,35.2971037,3a,75y,250.97h,81.3t,0.18r/data=!3m6!1e1!3m4!1swhpgEIWWoJapDZA_mbV1hA!2e0!7i13312!8i6656?hl=en)

[This is the sign of Khan el Basha](https://www.google.co.il/maps/@32.7012177,35.2970839,3a,15y,328.03h,90.81t/data=!3m6!1e1!3m4!1sdI6aL-B-06EQ7BfD-OZsTQ!2e0!7i13312!8i6656?hl=en), [you can park here](https://www.google.co.il/maps/place/Khan+El+Basha/@32.7014588,35.296772,3a,75y,90t/data=!3m8!1e2!3m6!1s-WPloln23Im8%2FWHkgjB9ovPI%2FAAAAAAAAVLI%2FlY8QgxYvtT4lzNh_7G_K78J-ey6UFzdoQCLIB!2e4!3e12!6s%2F%2Flh4.googleusercontent.com%2F-WPloln23Im8%2FWHkgjB9ovPI%2FAAAAAAAAVLI%2FlY8QgxYvtT4lzNh_7G_K78J-ey6UFzdoQCLIB%2Fw203-h152-k-no%2F!7i4032!8i3024!4m12!1m6!3m5!1s0x151c4dd353daffff:0xd3ad58016b38181f!2sKhan+El+Basha!8m2!3d32.7013951!4d35.296929!3m4!1s0x151c4dd353daffff:0xd3ad58016b38181f!8m2!3d32.7013951!4d35.296929?hl=en) but you'll probably [be charged money for it by the hour](https://www.google.co.il/maps/place/Khan+El+Basha/@32.7014588,35.296772,3a,75y,90t/data=!3m8!1e2!3m6!1s-WXyJRUIFY1M%2FWHkghE5NP5I%2FAAAAAAAAVLI%2FwxdF0ParIXoD2YQQnDFa9gVmms3FXNDSACLIB!2e4!3e12!6s%2F%2Flh4.googleusercontent.com%2F-WXyJRUIFY1M%2FWHkghE5NP5I%2FAAAAAAAAVLI%2FwxdF0ParIXoD2YQQnDFa9gVmms3FXNDSACLIB%2Fw203-h152-k-no%2F!7i4032!8i3024!4m12!1m6!3m5!1s0x151c4dd353daffff:0xd3ad58016b38181f!2sKhan+El+Basha!8m2!3d32.7013951!4d35.296929!3m4!1s0x151c4dd353daffff:0xd3ad58016b38181f!8m2!3d32.7013951!4d35.296929?hl=en)

Despite the fact that you're telling them not to hesitate, I think many of them will still hesitate anyway. So I think that we should emphasize making things easier for whoever it is you're mailing, like maybe we should make a FAQ page to prevent the need to ask questions like "do I need qualifications if I want to join the Campus?"

**Comment by Karyum** [comment]
I think first of all we need to add a google maps link cause as Joudy said not many people know where the Khan al Bahsa is. and another small thing is maybe change the word "alumni" to "graduates" just so it to be more clear.
Also you should maybe add another email of maybe Esraa me or whoever finished a FAC course ( or keep it the way it is if you like your inbox to get bombarded with emails of people asking questions about FAC :stuck_out_tongue: ) but again we should make it clear that they need to come to C4E and how they can get there.

**Comment by rebeccaradding** [comment]
**Update:** @Suuuuha will call applicants and her phone number will be on the email.

@HilbertSpitzer great points. I'll add more specific directions to Khan el-Basha. In our experience, FAQs can be helpful, but it's hard to keep them updated. Prepare yourself to answer a lot of the same questions in the Gitter channel!  

@Karyum I should have mentioned that I have a Waze link in the actual email. I was just lazy and didn't add it to this version. Is Google Maps preferable?

**Comment by HilbertSpitzer** [comment]
> you should maybe add another email of maybe Esraa me or whoever finished a FAC course ( or keep it the way it is if you like your inbox to get bombarded with emails of people asking questions about FAC 😛 )
 
I think you just got ignored Mario
Well, if anyone for whatever reason doesn't want to ask their question out in the open, then I give you permission to advertise this mail made just for students: HilbertSpitzer@protonmail.com
They can go ahead and bombard it, FACN2 members especially. It wasn't just a figure of speech when I said in the first SGC that people find it hard to admit their weaknesses out in the open, it's easier when it's just one-on-one, and probably even easier when done remotely by mail without eye-contact
To be honest, I would prefer that they do it on gitter, but I can understand why some might prefer not to do that, and if that solves their problem then so be it

> In our experience, FAQs can be helpful, but it's hard to keep them updated. Prepare yourself to answer a lot of the same questions in the Gitter channel!

It's not a matter of me not being willing to answer the same question, it's a matter of making things more efficient and easy for everyone.
Not sure if there's some major thing that I missed for FAQs to be hard to keep updated, but at least I don't think it's that hard to keep it updated on just C4E, how about I volunteer to compile the common questions we get from there to make a FAQ?

> I have a Waze link in the actual email

I saw that the foundersandcoders site itself also has it, I suppose [this is what you mean](https://mobile-web.world.waze.com/en_GB/meetup/location?h=svc451n7h). But I personally found the images of Google map more convenient, it's not even immediately clear how are you supposed to use waze, or is it just me who thinks that?

> cause as Joudy said

I don't think I have ever heard all of these 4 words together!
Did I change? Or did the world around me change?

> @Suuuuha will call applicants and her phone number will be on the email

👍 You know, it's really nice, seeing everyone standing together like this

**Comment by rebeccaradding** [comment]
@HilbertSpitzer:
- Thank you for volunteering your email, I'll certainly pass any questions on to you there!
- Would you mind raising a PR on `our-site` to change the link from Waze to Google (I put both in the email to applicants)
- Compiling a Nazareth-specific FAQ is a great idea - furthermore, when you get a feel for what people are asking about, you could open an issue for updates to https://foundersandcoders.com/programme/course-information/nazareth
