### ISSUE TITLE
Visiting Colleges and Universities

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/nazareth-outreach#3]
- One day in North
- One day in Central
- UKITH can help with logistics (transport)

**Comment by shiryz** [comment]
@rebeccaradding , any additional info would be helpful, like dates, which universities or what is the purpose of the visit?

**Comment by rebeccaradding** [comment]
@shiryz when I spoke with Dona she suggested it could be fruitful to set up visits to colleges and universities where you would give a brief talk and have a Q and A with interested students.

I spoke with her the day I left for holiday and apologize for not following up sooner - but if you and/or @esraajb are interested in committing time to this then I will help coordinate the visits and the UKITH will provide a driver for transport.

Worth our time?

**Comment by shiryz** [comment]
yes for sure, university students might be interested in joining the summer course and if not, we'll probably meet some interesting people working for interesting companies.

**Comment by sajedazoabi** [comment]
which universities and colleges we will visit?

**Comment by rebeccaradding** [comment]
@sajedazoabi I have opened an issue in `nazareth-programme` where it will have more visibility from others. 

https://github.com/foundersandcoders/nazareth-programme/issues/177
