### ISSUE TITLE
Future meetings

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/nazareth-outreach#5]
@esraajb @des-des and others...

I understand we may want to have a brief meeting this week to discuss adding a meeting at Khan el-Basha - suggest a date/time?

Let's also set meetings for April, May and June. Date and time preferences?

If we don't have anything up for discussion, we can decide not to meet - but having meetings on the calendar will allow those who want to participate to plan to attend.

**Comment by des-des** [comment]
yes lets have a meeting next week

**Comment by rebeccaradding** [comment]
Works for me, what time do you prefer?

**Comment by des-des** [comment]
11am my time?

**Comment by rebeccaradding** [comment]
Unfortunately I have another meeting at that time that I can't move, can we do 10 or 12?

**Comment by rebeccaradding** [comment]
@des-des @esraajb when shall we reschedule?

**Comment by des-des** [comment]
@rebeccaradding next Wednesday?
