### ISSUE TITLE
Create a Coding for Everyone group on FB?

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/nazareth-outreach#6]
It has been suggested that we create a Coding for Everyone group, rather than regular weekly events, so that we can simply post updates there with the latest date/time/location.

Thoughts?

**Comment by jsms90** [comment]
If we have the necessary people to keep it updated :+1:

**Comment by rebeccaradding** [comment]
@jsms90 sorry I should have specified, for Nazareth, since we aren't using Meetup.com, and we have to invite people over again every week on FB.
